import { React, useState, useEffect } from 'react'
import { Loader, Card, FormField } from '../components'

const RenderCards = ({ data, title }) => {
  if (data?.length > 0) {
    return data.map((post) => <Card key={post._id}{...post} />)
  }

  return (
    <h2 className='mt-5 fond-bold'>{title}</h2>
  )


}

const Home = () => {
  const [loading, setLoading] = useState(false)

  const [searchText, setsearchText] = useState('')

  return (
    <section className='max-w-7xl mx-auto'>
      <div>
        <h1 className='font-extrabold text-[32px]'>Gallery</h1>
        <p className='text-[16px]'>Browse through a collection of imaginative and visually stunning images generated by AI</p>
      </div>
      <div className='mt-16'>
        <FormField  />
      </div>

      <div className='mt-10'>
        {loading ? (
          <div className='flex justify-center items-center'>
            <Loader />
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className='font-medium text-xl mb-3'>Showing result for: {searchText}</h2>
            )}
            <div className='grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3'></div>
            {searchText ? (
              <RenderCards
                data={[]}
                title="No search results found" />
            ) : (
              <RenderCards
                data={[]}
                title="No posts found" />
            )}
          </>
        )}
      </div>
    </section>
  )
}

export default Home